apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rosmarium.fullname" . }}-server
  labels:
    {{- include "rosmarium.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.server }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rosmarium.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rosmarium.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/rosmarium-server:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rosmarium.fullname" . }}-config
          env:
            - name: DATABASE_URL
              value: {{ .Values.config.databaseUrl | quote }}
            - name: REDIS_URL
              value: {{ .Values.config.redisUrl | quote }}
            - name: JWT_SECRET
              value: {{ .Values.config.jwtSecret | quote }}
            - name: ANTHROPIC_API_KEY
              value: {{ .Values.config.anthropicApiKey | quote }}
            - name: COHERE_API_KEY
              value: {{ .Values.config.cohereApiKey | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.server.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.server.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
