apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
