import type { FastifyInstance } from "fastify";
import healthRoutes from "./health.js";
import authRoutes from "./auth/index.js";
import contentRoutes from "./content/index.js";
import webhookRoutes from "./webhooks.js";
import searchRoutes from "./search.js";
import ragRoutes from "./rag.js";
import intelligenceRoutes from "./intelligence.js";
import adminRoutes from "./admin.js";
import graphRoutes from "./graph.js";
import userRoutes from "./users.js";
import { previewRoutes } from "../modules/preview/preview.routes.js";
import { workflowRoutes } from "../modules/workflow/workflow.routes.js";
import { branchRoutes } from "../modules/branches/branch.routes.js";
import { presenceRoutes } from "../modules/collab/presence.routes.js";
import { commentsRoutes } from "../modules/collab/comments.routes.js";
import { generationRoutes } from "../modules/intelligence/generation.routes.js";
import { translationRoutes } from "../modules/i18n/translation.routes.js";
import { aiGovernanceRoutes } from "../modules/intelligence/ai-governance.routes.js";
import { mediaRoutes } from "../modules/media/media.routes.js";
import { workspaceRoutes } from "../modules/workspaces/workspace.routes.js";
import { governanceRoutes } from "../modules/governance/governance.routes.js";
import { auditRoutes } from "../modules/audit/audit.routes.js";
import { assetsRoutes } from "./assets.js";
import ingestorRoutes from "./ingestor.js";

export const registerRoutes = async (app: FastifyInstance) => {
    await app.register(healthRoutes);
    await app.register(authRoutes);
    await app.register(contentRoutes);
    await app.register(webhookRoutes);
    await app.register(searchRoutes);
    await app.register(ragRoutes);
    await app.register(intelligenceRoutes);
    await app.register(adminRoutes);
    await app.register(graphRoutes);
    await app.register(userRoutes);
    await app.register(previewRoutes);
    await app.register(workflowRoutes, { prefix: "/api/workflow" });
    await app.register(branchRoutes, { prefix: "/api/branches" });
    await app.register(presenceRoutes, { prefix: "/api/collab" });
    await app.register(commentsRoutes, { prefix: "/api/collab" });
    await app.register(generationRoutes, { prefix: "/api/ai" });
    await app.register(translationRoutes, { prefix: "/api/ai" });
    await app.register(aiGovernanceRoutes, { prefix: "/api/ai/governance" });
    await app.register(mediaRoutes, { prefix: "/api/media" });
    await app.register(workspaceRoutes, { prefix: "/api/workspaces" });
    await app.register(governanceRoutes, { prefix: "/api/governance" });
    await app.register(auditRoutes, { prefix: "/api/audit" });
    await app.register(assetsRoutes, { prefix: "/api/assets" });
    await app.register(ingestorRoutes);
};
